apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:  #Pods que serão expostos pelo cluster
    app: mongodb
  ports:
  - port: 27017   #porta do serviço
    targetPort: 27017   #porta do container
  type: ClusterIP
  
