apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
  - port: 80    #por ser uma aplicação web a porta padrão é 80
    targetPort: 5000  #Porta da aplicação
    nodePort: 30000   #Por utiliza um nodeport
  type: NodePort
